sudo: true
language: node_js
os:
  - linux
  - osx
  - windows
node_js:
  - "10"
script:
  - npm run ci:test
  - npm run build
deploy:
  - provider: script
    skip_cleanup: true
    script: ./travis-ci-deploy.sh production
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: ./travis-ci-deploy.sh staging
    on:
      branch: staging
