import books from 'books-of-the-bible'
import { writeFile } from 'node:fs/promises'
import keyMaster from 'key-master'
import { join } from 'node:path'

import { get_book_id } from '../../client/lib/get_id.ts'

main()

async function main() {
	const bookIds = books.map(bookToIds)

	const shortIdToLongIds = keyMaster(() => [])

	const shortIdToLongId = Object.create(null)

	bookIds.forEach(({ longId, shortIds }) => {
		shortIds.forEach(shortId => {
			shortIdToLongIds.get(shortId).push(longId)
		})
	})

	bookIds.forEach(({ longId, shortIds }) => {
		const sortedShortIds = sortShortToLong(shortIds)

		sortedShortIds.forEach(shortId => {
			const shorterVersionWasUsedAlready = getAllShortIds(shortId).some(
				id => shortIdToLongId[id]
			)

			const isUnique = shortIdToLongIds.get(shortId).length === 1
			if (!shorterVersionWasUsedAlready && isUnique) {
				shortIdToLongId[shortId] = longId
			}
		})
	})

	const longest_unique_key = Object.keys(shortIdToLongId).reduce(
		(longest, key) => Math.max(longest, key.length),
		0
	)

	const output = {
		longest_unique_key,
		short_id_to_long_id: shortIdToLongId,
	}

	await writeFile(join(import.meta.url, '../../client/lib/short_book_names.ts'),
		`/* auto-generated by generation-scripts/generate-book-shortcut-map */

interface ShortBookNames {
	longest_unique_key: number
	short_id_to_long_id: Record<string, string>
}

const short_book_names: ShortBookNames = ${ JSON.stringify(output, null, '\t') }

export default short_book_names
`)
}

function getFirstElement(array, condition) {
	return array.reduce((found, element) => {
		if (found) {
			return found
		}

		if (condition(element)) {
			return element
		}
	}, null)
}

function sortShortToLong(ids) {
	return ids.slice().sort((a, b) => a.length - b.length)
}

function bookToIds(book) {
	const longId = get_book_id(book.name)
	const aliasIds = book.aliases.map(alias => get_book_id(alias))

	const uniqueShortIds = new Set()

	const addAllShortIdsToSet = id => getAllShortIds(id).forEach(
		shortId => uniqueShortIds.add(shortId)
	)

	addAllShortIdsToSet(longId)
	aliasIds.forEach(addAllShortIdsToSet)

	return {
		longId,
		shortIds: Array.from(uniqueShortIds),
	}
}

function getAllShortIds(id) {
	let lastShortId = ``
	return id.split(``).map(char => {
		const thisShortId = lastShortId + char
		lastShortId += char
		return thisShortId
	})
}
